#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Catalog")]
	public partial class DBCatalogDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_EnderecoEstabelecimento(tb_EnderecoEstabelecimento instance);
    partial void Updatetb_EnderecoEstabelecimento(tb_EnderecoEstabelecimento instance);
    partial void Deletetb_EnderecoEstabelecimento(tb_EnderecoEstabelecimento instance);
    partial void Inserttb_Chave(tb_Chave instance);
    partial void Updatetb_Chave(tb_Chave instance);
    partial void Deletetb_Chave(tb_Chave instance);
    partial void Inserttb_Estabelecimento(tb_Estabelecimento instance);
    partial void Updatetb_Estabelecimento(tb_Estabelecimento instance);
    partial void Deletetb_Estabelecimento(tb_Estabelecimento instance);
    partial void Inserttb_Fabricante(tb_Fabricante instance);
    partial void Updatetb_Fabricante(tb_Fabricante instance);
    partial void Deletetb_Fabricante(tb_Fabricante instance);
    partial void Inserttb_Item(tb_Item instance);
    partial void Updatetb_Item(tb_Item instance);
    partial void Deletetb_Item(tb_Item instance);
    partial void Inserttb_Lista(tb_Lista instance);
    partial void Updatetb_Lista(tb_Lista instance);
    partial void Deletetb_Lista(tb_Lista instance);
    partial void Inserttb_Produto(tb_Produto instance);
    partial void Updatetb_Produto(tb_Produto instance);
    partial void Deletetb_Produto(tb_Produto instance);
    partial void Inserttb_ProdutoDaLista(tb_ProdutoDaLista instance);
    partial void Updatetb_ProdutoDaLista(tb_ProdutoDaLista instance);
    partial void Deletetb_ProdutoDaLista(tb_ProdutoDaLista instance);
    partial void Inserttb_SenhaAlternativa(tb_SenhaAlternativa instance);
    partial void Updatetb_SenhaAlternativa(tb_SenhaAlternativa instance);
    partial void Deletetb_SenhaAlternativa(tb_SenhaAlternativa instance);
    partial void Inserttb_Tipo(tb_Tipo instance);
    partial void Updatetb_Tipo(tb_Tipo instance);
    partial void Deletetb_Tipo(tb_Tipo instance);
    partial void Inserttb_Usuario(tb_Usuario instance);
    partial void Updatetb_Usuario(tb_Usuario instance);
    partial void Deletetb_Usuario(tb_Usuario instance);
    #endregion
		
		public DBCatalogDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CatalogConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_EnderecoEstabelecimento> tb_EnderecoEstabelecimentos
		{
			get
			{
				return this.GetTable<tb_EnderecoEstabelecimento>();
			}
		}
		
		public System.Data.Linq.Table<tb_Chave> tb_Chaves
		{
			get
			{
				return this.GetTable<tb_Chave>();
			}
		}
		
		public System.Data.Linq.Table<tb_Estabelecimento> tb_Estabelecimentos
		{
			get
			{
				return this.GetTable<tb_Estabelecimento>();
			}
		}
		
		public System.Data.Linq.Table<tb_Fabricante> tb_Fabricantes
		{
			get
			{
				return this.GetTable<tb_Fabricante>();
			}
		}
		
		public System.Data.Linq.Table<tb_Item> tb_Items
		{
			get
			{
				return this.GetTable<tb_Item>();
			}
		}
		
		public System.Data.Linq.Table<tb_Lista> tb_Listas
		{
			get
			{
				return this.GetTable<tb_Lista>();
			}
		}
		
		public System.Data.Linq.Table<tb_Produto> tb_Produtos
		{
			get
			{
				return this.GetTable<tb_Produto>();
			}
		}
		
		public System.Data.Linq.Table<tb_ProdutoDaLista> tb_ProdutoDaListas
		{
			get
			{
				return this.GetTable<tb_ProdutoDaLista>();
			}
		}
		
		public System.Data.Linq.Table<tb_SenhaAlternativa> tb_SenhaAlternativas
		{
			get
			{
				return this.GetTable<tb_SenhaAlternativa>();
			}
		}
		
		public System.Data.Linq.Table<tb_Tipo> tb_Tipos
		{
			get
			{
				return this.GetTable<tb_Tipo>();
			}
		}
		
		public System.Data.Linq.Table<tb_Usuario> tb_Usuarios
		{
			get
			{
				return this.GetTable<tb_Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_EnderecoEstabelecimento")]
	public partial class tb_EnderecoEstabelecimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _rua;
		
		private string _cidade;
		
		private string _estado;
		
		private string _numero;
		
		private string _cep;
		
		private System.Nullable<double> _latitude;
		
		private System.Nullable<double> _longitude;
		
		private System.Nullable<int> _idEstabelecimento;
		
		private EntityRef<tb_Estabelecimento> _tb_Estabelecimento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnruaChanging(string value);
    partial void OnruaChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnlatitudeChanging(System.Nullable<double> value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(System.Nullable<double> value);
    partial void OnlongitudeChanged();
    partial void OnidEstabelecimentoChanging(System.Nullable<int> value);
    partial void OnidEstabelecimentoChanged();
    #endregion
		
		public tb_EnderecoEstabelecimento()
		{
			this._tb_Estabelecimento = default(EntityRef<tb_Estabelecimento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rua", DbType="VarChar(100)")]
		public string rua
		{
			get
			{
				return this._rua;
			}
			set
			{
				if ((this._rua != value))
				{
					this.OnruaChanging(value);
					this.SendPropertyChanging();
					this._rua = value;
					this.SendPropertyChanged("rua");
					this.OnruaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(100)")]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(100)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(50)")]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(100)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Float")]
		public System.Nullable<double> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Float")]
		public System.Nullable<double> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstabelecimento", DbType="Int")]
		public System.Nullable<int> idEstabelecimento
		{
			get
			{
				return this._idEstabelecimento;
			}
			set
			{
				if ((this._idEstabelecimento != value))
				{
					if (this._tb_Estabelecimento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEstabelecimentoChanging(value);
					this.SendPropertyChanging();
					this._idEstabelecimento = value;
					this.SendPropertyChanged("idEstabelecimento");
					this.OnidEstabelecimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Estabelecimento_tb_EnderecoEstabelecimento", Storage="_tb_Estabelecimento", ThisKey="idEstabelecimento", OtherKey="id", IsForeignKey=true)]
		public tb_Estabelecimento tb_Estabelecimento
		{
			get
			{
				return this._tb_Estabelecimento.Entity;
			}
			set
			{
				tb_Estabelecimento previousValue = this._tb_Estabelecimento.Entity;
				if (((previousValue != value) 
							|| (this._tb_Estabelecimento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Estabelecimento.Entity = null;
						previousValue.tb_EnderecoEstabelecimentos.Remove(this);
					}
					this._tb_Estabelecimento.Entity = value;
					if ((value != null))
					{
						value.tb_EnderecoEstabelecimentos.Add(this);
						this._idEstabelecimento = value.id;
					}
					else
					{
						this._idEstabelecimento = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Estabelecimento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Chave")]
	public partial class tb_Chave : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private string _token;
		
		private System.Nullable<System.TimeSpan> _ultimoAcesso;
		
		private EntityRef<tb_Usuario> _tb_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OntokenChanging(string value);
    partial void OntokenChanged();
    partial void OnultimoAcessoChanging(System.Nullable<System.TimeSpan> value);
    partial void OnultimoAcessoChanged();
    #endregion
		
		public tb_Chave()
		{
			this._tb_Usuario = default(EntityRef<tb_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._tb_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(50)")]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ultimoAcesso", DbType="Time")]
		public System.Nullable<System.TimeSpan> ultimoAcesso
		{
			get
			{
				return this._ultimoAcesso;
			}
			set
			{
				if ((this._ultimoAcesso != value))
				{
					this.OnultimoAcessoChanging(value);
					this.SendPropertyChanging();
					this._ultimoAcesso = value;
					this.SendPropertyChanged("ultimoAcesso");
					this.OnultimoAcessoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Chave", Storage="_tb_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public tb_Usuario tb_Usuario
		{
			get
			{
				return this._tb_Usuario.Entity;
			}
			set
			{
				tb_Usuario previousValue = this._tb_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Usuario.Entity = null;
						previousValue.tb_Chave = null;
					}
					this._tb_Usuario.Entity = value;
					if ((value != null))
					{
						value.tb_Chave = this;
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("tb_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Estabelecimento")]
	public partial class tb_Estabelecimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _estabelecimento;
		
		private EntitySet<tb_EnderecoEstabelecimento> _tb_EnderecoEstabelecimentos;
		
		private EntitySet<tb_Item> _tb_Items;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnestabelecimentoChanging(string value);
    partial void OnestabelecimentoChanged();
    #endregion
		
		public tb_Estabelecimento()
		{
			this._tb_EnderecoEstabelecimentos = new EntitySet<tb_EnderecoEstabelecimento>(new Action<tb_EnderecoEstabelecimento>(this.attach_tb_EnderecoEstabelecimentos), new Action<tb_EnderecoEstabelecimento>(this.detach_tb_EnderecoEstabelecimentos));
			this._tb_Items = new EntitySet<tb_Item>(new Action<tb_Item>(this.attach_tb_Items), new Action<tb_Item>(this.detach_tb_Items));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estabelecimento", DbType="VarChar(50)")]
		public string estabelecimento
		{
			get
			{
				return this._estabelecimento;
			}
			set
			{
				if ((this._estabelecimento != value))
				{
					this.OnestabelecimentoChanging(value);
					this.SendPropertyChanging();
					this._estabelecimento = value;
					this.SendPropertyChanged("estabelecimento");
					this.OnestabelecimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Estabelecimento_tb_EnderecoEstabelecimento", Storage="_tb_EnderecoEstabelecimentos", ThisKey="id", OtherKey="idEstabelecimento")]
		public EntitySet<tb_EnderecoEstabelecimento> tb_EnderecoEstabelecimentos
		{
			get
			{
				return this._tb_EnderecoEstabelecimentos;
			}
			set
			{
				this._tb_EnderecoEstabelecimentos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Estabelecimento_tb_Item", Storage="_tb_Items", ThisKey="id", OtherKey="idEstabelecimento")]
		public EntitySet<tb_Item> tb_Items
		{
			get
			{
				return this._tb_Items;
			}
			set
			{
				this._tb_Items.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_EnderecoEstabelecimentos(tb_EnderecoEstabelecimento entity)
		{
			this.SendPropertyChanging();
			entity.tb_Estabelecimento = this;
		}
		
		private void detach_tb_EnderecoEstabelecimentos(tb_EnderecoEstabelecimento entity)
		{
			this.SendPropertyChanging();
			entity.tb_Estabelecimento = null;
		}
		
		private void attach_tb_Items(tb_Item entity)
		{
			this.SendPropertyChanging();
			entity.tb_Estabelecimento = this;
		}
		
		private void detach_tb_Items(tb_Item entity)
		{
			this.SendPropertyChanging();
			entity.tb_Estabelecimento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Fabricante")]
	public partial class tb_Fabricante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _fabricante;
		
		private EntitySet<tb_Produto> _tb_Produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfabricanteChanging(string value);
    partial void OnfabricanteChanged();
    #endregion
		
		public tb_Fabricante()
		{
			this._tb_Produtos = new EntitySet<tb_Produto>(new Action<tb_Produto>(this.attach_tb_Produtos), new Action<tb_Produto>(this.detach_tb_Produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fabricante", DbType="VarChar(50)")]
		public string fabricante
		{
			get
			{
				return this._fabricante;
			}
			set
			{
				if ((this._fabricante != value))
				{
					this.OnfabricanteChanging(value);
					this.SendPropertyChanging();
					this._fabricante = value;
					this.SendPropertyChanged("fabricante");
					this.OnfabricanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Fabricante_tb_Produto", Storage="_tb_Produtos", ThisKey="id", OtherKey="idFabricante")]
		public EntitySet<tb_Produto> tb_Produtos
		{
			get
			{
				return this._tb_Produtos;
			}
			set
			{
				this._tb_Produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Produtos(tb_Produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_Fabricante = this;
		}
		
		private void detach_tb_Produtos(tb_Produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_Fabricante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Item")]
	public partial class tb_Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<double> _preco;
		
		private System.Nullable<System.DateTime> _compraRecente;
		
		private System.Nullable<int> _qualificacao;
		
		private System.Nullable<int> _idEstabelecimento;
		
		private System.Nullable<int> _idProduto;
		
		private EntityRef<tb_Estabelecimento> _tb_Estabelecimento;
		
		private EntityRef<tb_Produto> _tb_Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnprecoChanging(System.Nullable<double> value);
    partial void OnprecoChanged();
    partial void OncompraRecenteChanging(System.Nullable<System.DateTime> value);
    partial void OncompraRecenteChanged();
    partial void OnqualificacaoChanging(System.Nullable<int> value);
    partial void OnqualificacaoChanged();
    partial void OnidEstabelecimentoChanging(System.Nullable<int> value);
    partial void OnidEstabelecimentoChanged();
    partial void OnidProdutoChanging(System.Nullable<int> value);
    partial void OnidProdutoChanged();
    #endregion
		
		public tb_Item()
		{
			this._tb_Estabelecimento = default(EntityRef<tb_Estabelecimento>);
			this._tb_Produto = default(EntityRef<tb_Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preco", DbType="Float")]
		public System.Nullable<double> preco
		{
			get
			{
				return this._preco;
			}
			set
			{
				if ((this._preco != value))
				{
					this.OnprecoChanging(value);
					this.SendPropertyChanging();
					this._preco = value;
					this.SendPropertyChanged("preco");
					this.OnprecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compraRecente", DbType="Date")]
		public System.Nullable<System.DateTime> compraRecente
		{
			get
			{
				return this._compraRecente;
			}
			set
			{
				if ((this._compraRecente != value))
				{
					this.OncompraRecenteChanging(value);
					this.SendPropertyChanging();
					this._compraRecente = value;
					this.SendPropertyChanged("compraRecente");
					this.OncompraRecenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualificacao", DbType="Int")]
		public System.Nullable<int> qualificacao
		{
			get
			{
				return this._qualificacao;
			}
			set
			{
				if ((this._qualificacao != value))
				{
					this.OnqualificacaoChanging(value);
					this.SendPropertyChanging();
					this._qualificacao = value;
					this.SendPropertyChanged("qualificacao");
					this.OnqualificacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstabelecimento", DbType="Int")]
		public System.Nullable<int> idEstabelecimento
		{
			get
			{
				return this._idEstabelecimento;
			}
			set
			{
				if ((this._idEstabelecimento != value))
				{
					if (this._tb_Estabelecimento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEstabelecimentoChanging(value);
					this.SendPropertyChanging();
					this._idEstabelecimento = value;
					this.SendPropertyChanged("idEstabelecimento");
					this.OnidEstabelecimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduto", DbType="Int")]
		public System.Nullable<int> idProduto
		{
			get
			{
				return this._idProduto;
			}
			set
			{
				if ((this._idProduto != value))
				{
					if (this._tb_Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProdutoChanging(value);
					this.SendPropertyChanging();
					this._idProduto = value;
					this.SendPropertyChanged("idProduto");
					this.OnidProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Estabelecimento_tb_Item", Storage="_tb_Estabelecimento", ThisKey="idEstabelecimento", OtherKey="id", IsForeignKey=true)]
		public tb_Estabelecimento tb_Estabelecimento
		{
			get
			{
				return this._tb_Estabelecimento.Entity;
			}
			set
			{
				tb_Estabelecimento previousValue = this._tb_Estabelecimento.Entity;
				if (((previousValue != value) 
							|| (this._tb_Estabelecimento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Estabelecimento.Entity = null;
						previousValue.tb_Items.Remove(this);
					}
					this._tb_Estabelecimento.Entity = value;
					if ((value != null))
					{
						value.tb_Items.Add(this);
						this._idEstabelecimento = value.id;
					}
					else
					{
						this._idEstabelecimento = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Estabelecimento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Produto_tb_Item", Storage="_tb_Produto", ThisKey="idProduto", OtherKey="id", IsForeignKey=true)]
		public tb_Produto tb_Produto
		{
			get
			{
				return this._tb_Produto.Entity;
			}
			set
			{
				tb_Produto previousValue = this._tb_Produto.Entity;
				if (((previousValue != value) 
							|| (this._tb_Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Produto.Entity = null;
						previousValue.tb_Items.Remove(this);
					}
					this._tb_Produto.Entity = value;
					if ((value != null))
					{
						value.tb_Items.Add(this);
						this._idProduto = value.id;
					}
					else
					{
						this._idProduto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Lista")]
	public partial class tb_Lista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _titulo;
		
		private System.Nullable<int> _idUsuario;
		
		private EntitySet<tb_ProdutoDaLista> _tb_ProdutoDaListas;
		
		private EntityRef<tb_Usuario> _tb_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OnidUsuarioChanging(System.Nullable<int> value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public tb_Lista()
		{
			this._tb_ProdutoDaListas = new EntitySet<tb_ProdutoDaLista>(new Action<tb_ProdutoDaLista>(this.attach_tb_ProdutoDaListas), new Action<tb_ProdutoDaLista>(this.detach_tb_ProdutoDaListas));
			this._tb_Usuario = default(EntityRef<tb_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(50)")]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int")]
		public System.Nullable<int> idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._tb_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Lista_tb_ProdutoDaLista", Storage="_tb_ProdutoDaListas", ThisKey="id", OtherKey="idLista")]
		public EntitySet<tb_ProdutoDaLista> tb_ProdutoDaListas
		{
			get
			{
				return this._tb_ProdutoDaListas;
			}
			set
			{
				this._tb_ProdutoDaListas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Lista", Storage="_tb_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public tb_Usuario tb_Usuario
		{
			get
			{
				return this._tb_Usuario.Entity;
			}
			set
			{
				tb_Usuario previousValue = this._tb_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Usuario.Entity = null;
						previousValue.tb_Listas.Remove(this);
					}
					this._tb_Usuario.Entity = value;
					if ((value != null))
					{
						value.tb_Listas.Add(this);
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_ProdutoDaListas(tb_ProdutoDaLista entity)
		{
			this.SendPropertyChanging();
			entity.tb_Lista = this;
		}
		
		private void detach_tb_ProdutoDaListas(tb_ProdutoDaLista entity)
		{
			this.SendPropertyChanging();
			entity.tb_Lista = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Produto")]
	public partial class tb_Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _codigoDeBarras;
		
		private System.Nullable<int> _idFabricante;
		
		private System.Nullable<int> _idTipo;
		
		private EntitySet<tb_Item> _tb_Items;
		
		private EntitySet<tb_ProdutoDaLista> _tb_ProdutoDaListas;
		
		private EntityRef<tb_Fabricante> _tb_Fabricante;
		
		private EntityRef<tb_Tipo> _tb_Tipo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OncodigoDeBarrasChanging(string value);
    partial void OncodigoDeBarrasChanged();
    partial void OnidFabricanteChanging(System.Nullable<int> value);
    partial void OnidFabricanteChanged();
    partial void OnidTipoChanging(System.Nullable<int> value);
    partial void OnidTipoChanged();
    #endregion
		
		public tb_Produto()
		{
			this._tb_Items = new EntitySet<tb_Item>(new Action<tb_Item>(this.attach_tb_Items), new Action<tb_Item>(this.detach_tb_Items));
			this._tb_ProdutoDaListas = new EntitySet<tb_ProdutoDaLista>(new Action<tb_ProdutoDaLista>(this.attach_tb_ProdutoDaListas), new Action<tb_ProdutoDaLista>(this.detach_tb_ProdutoDaListas));
			this._tb_Fabricante = default(EntityRef<tb_Fabricante>);
			this._tb_Tipo = default(EntityRef<tb_Tipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(100)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDeBarras", DbType="VarChar(50)")]
		public string codigoDeBarras
		{
			get
			{
				return this._codigoDeBarras;
			}
			set
			{
				if ((this._codigoDeBarras != value))
				{
					this.OncodigoDeBarrasChanging(value);
					this.SendPropertyChanging();
					this._codigoDeBarras = value;
					this.SendPropertyChanged("codigoDeBarras");
					this.OncodigoDeBarrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFabricante", DbType="Int")]
		public System.Nullable<int> idFabricante
		{
			get
			{
				return this._idFabricante;
			}
			set
			{
				if ((this._idFabricante != value))
				{
					if (this._tb_Fabricante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidFabricanteChanging(value);
					this.SendPropertyChanging();
					this._idFabricante = value;
					this.SendPropertyChanged("idFabricante");
					this.OnidFabricanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipo", DbType="Int")]
		public System.Nullable<int> idTipo
		{
			get
			{
				return this._idTipo;
			}
			set
			{
				if ((this._idTipo != value))
				{
					if (this._tb_Tipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoChanging(value);
					this.SendPropertyChanging();
					this._idTipo = value;
					this.SendPropertyChanged("idTipo");
					this.OnidTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Produto_tb_Item", Storage="_tb_Items", ThisKey="id", OtherKey="idProduto")]
		public EntitySet<tb_Item> tb_Items
		{
			get
			{
				return this._tb_Items;
			}
			set
			{
				this._tb_Items.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Produto_tb_ProdutoDaLista", Storage="_tb_ProdutoDaListas", ThisKey="id", OtherKey="idProduto")]
		public EntitySet<tb_ProdutoDaLista> tb_ProdutoDaListas
		{
			get
			{
				return this._tb_ProdutoDaListas;
			}
			set
			{
				this._tb_ProdutoDaListas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Fabricante_tb_Produto", Storage="_tb_Fabricante", ThisKey="idFabricante", OtherKey="id", IsForeignKey=true)]
		public tb_Fabricante tb_Fabricante
		{
			get
			{
				return this._tb_Fabricante.Entity;
			}
			set
			{
				tb_Fabricante previousValue = this._tb_Fabricante.Entity;
				if (((previousValue != value) 
							|| (this._tb_Fabricante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Fabricante.Entity = null;
						previousValue.tb_Produtos.Remove(this);
					}
					this._tb_Fabricante.Entity = value;
					if ((value != null))
					{
						value.tb_Produtos.Add(this);
						this._idFabricante = value.id;
					}
					else
					{
						this._idFabricante = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Fabricante");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Tipo_tb_Produto", Storage="_tb_Tipo", ThisKey="idTipo", OtherKey="id", IsForeignKey=true)]
		public tb_Tipo tb_Tipo
		{
			get
			{
				return this._tb_Tipo.Entity;
			}
			set
			{
				tb_Tipo previousValue = this._tb_Tipo.Entity;
				if (((previousValue != value) 
							|| (this._tb_Tipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Tipo.Entity = null;
						previousValue.tb_Produtos.Remove(this);
					}
					this._tb_Tipo.Entity = value;
					if ((value != null))
					{
						value.tb_Produtos.Add(this);
						this._idTipo = value.id;
					}
					else
					{
						this._idTipo = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Tipo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Items(tb_Item entity)
		{
			this.SendPropertyChanging();
			entity.tb_Produto = this;
		}
		
		private void detach_tb_Items(tb_Item entity)
		{
			this.SendPropertyChanging();
			entity.tb_Produto = null;
		}
		
		private void attach_tb_ProdutoDaListas(tb_ProdutoDaLista entity)
		{
			this.SendPropertyChanging();
			entity.tb_Produto = this;
		}
		
		private void detach_tb_ProdutoDaListas(tb_ProdutoDaLista entity)
		{
			this.SendPropertyChanging();
			entity.tb_Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ProdutoDaLista")]
	public partial class tb_ProdutoDaLista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _quantidade;
		
		private System.Nullable<int> _idProduto;
		
		private System.Nullable<int> _idLista;
		
		private EntityRef<tb_Lista> _tb_Lista;
		
		private EntityRef<tb_Produto> _tb_Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnquantidadeChanging(System.Nullable<int> value);
    partial void OnquantidadeChanged();
    partial void OnidProdutoChanging(System.Nullable<int> value);
    partial void OnidProdutoChanged();
    partial void OnidListaChanging(System.Nullable<int> value);
    partial void OnidListaChanged();
    #endregion
		
		public tb_ProdutoDaLista()
		{
			this._tb_Lista = default(EntityRef<tb_Lista>);
			this._tb_Produto = default(EntityRef<tb_Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int")]
		public System.Nullable<int> quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProduto", DbType="Int")]
		public System.Nullable<int> idProduto
		{
			get
			{
				return this._idProduto;
			}
			set
			{
				if ((this._idProduto != value))
				{
					if (this._tb_Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProdutoChanging(value);
					this.SendPropertyChanging();
					this._idProduto = value;
					this.SendPropertyChanged("idProduto");
					this.OnidProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLista", DbType="Int")]
		public System.Nullable<int> idLista
		{
			get
			{
				return this._idLista;
			}
			set
			{
				if ((this._idLista != value))
				{
					if (this._tb_Lista.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidListaChanging(value);
					this.SendPropertyChanging();
					this._idLista = value;
					this.SendPropertyChanged("idLista");
					this.OnidListaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Lista_tb_ProdutoDaLista", Storage="_tb_Lista", ThisKey="idLista", OtherKey="id", IsForeignKey=true)]
		public tb_Lista tb_Lista
		{
			get
			{
				return this._tb_Lista.Entity;
			}
			set
			{
				tb_Lista previousValue = this._tb_Lista.Entity;
				if (((previousValue != value) 
							|| (this._tb_Lista.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Lista.Entity = null;
						previousValue.tb_ProdutoDaListas.Remove(this);
					}
					this._tb_Lista.Entity = value;
					if ((value != null))
					{
						value.tb_ProdutoDaListas.Add(this);
						this._idLista = value.id;
					}
					else
					{
						this._idLista = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Lista");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Produto_tb_ProdutoDaLista", Storage="_tb_Produto", ThisKey="idProduto", OtherKey="id", IsForeignKey=true)]
		public tb_Produto tb_Produto
		{
			get
			{
				return this._tb_Produto.Entity;
			}
			set
			{
				tb_Produto previousValue = this._tb_Produto.Entity;
				if (((previousValue != value) 
							|| (this._tb_Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Produto.Entity = null;
						previousValue.tb_ProdutoDaListas.Remove(this);
					}
					this._tb_Produto.Entity = value;
					if ((value != null))
					{
						value.tb_ProdutoDaListas.Add(this);
						this._idProduto = value.id;
					}
					else
					{
						this._idProduto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_SenhaAlternativa")]
	public partial class tb_SenhaAlternativa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private string _senha;
		
		private System.Nullable<System.DateTime> _dataDeCriacao;
		
		private EntityRef<tb_Usuario> _tb_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void OndataDeCriacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataDeCriacaoChanged();
    #endregion
		
		public tb_SenhaAlternativa()
		{
			this._tb_Usuario = default(EntityRef<tb_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._tb_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(50)")]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataDeCriacao", DbType="Date")]
		public System.Nullable<System.DateTime> dataDeCriacao
		{
			get
			{
				return this._dataDeCriacao;
			}
			set
			{
				if ((this._dataDeCriacao != value))
				{
					this.OndataDeCriacaoChanging(value);
					this.SendPropertyChanging();
					this._dataDeCriacao = value;
					this.SendPropertyChanged("dataDeCriacao");
					this.OndataDeCriacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_SenhaAlternativa", Storage="_tb_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public tb_Usuario tb_Usuario
		{
			get
			{
				return this._tb_Usuario.Entity;
			}
			set
			{
				tb_Usuario previousValue = this._tb_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Usuario.Entity = null;
						previousValue.tb_SenhaAlternativa = null;
					}
					this._tb_Usuario.Entity = value;
					if ((value != null))
					{
						value.tb_SenhaAlternativa = this;
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("tb_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Tipo")]
	public partial class tb_Tipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tipo;
		
		private EntitySet<tb_Produto> _tb_Produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public tb_Tipo()
		{
			this._tb_Produtos = new EntitySet<tb_Produto>(new Action<tb_Produto>(this.attach_tb_Produtos), new Action<tb_Produto>(this.detach_tb_Produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(50)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Tipo_tb_Produto", Storage="_tb_Produtos", ThisKey="id", OtherKey="idTipo")]
		public EntitySet<tb_Produto> tb_Produtos
		{
			get
			{
				return this._tb_Produtos;
			}
			set
			{
				this._tb_Produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Produtos(tb_Produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_Tipo = this;
		}
		
		private void detach_tb_Produtos(tb_Produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_Tipo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Usuario")]
	public partial class tb_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _senha;
		
		private string _nome;
		
		private EntityRef<tb_Chave> _tb_Chave;
		
		private EntitySet<tb_Lista> _tb_Listas;
		
		private EntityRef<tb_SenhaAlternativa> _tb_SenhaAlternativa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    #endregion
		
		public tb_Usuario()
		{
			this._tb_Chave = default(EntityRef<tb_Chave>);
			this._tb_Listas = new EntitySet<tb_Lista>(new Action<tb_Lista>(this.attach_tb_Listas), new Action<tb_Lista>(this.detach_tb_Listas));
			this._tb_SenhaAlternativa = default(EntityRef<tb_SenhaAlternativa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Chave", Storage="_tb_Chave", ThisKey="id", OtherKey="idUsuario", IsUnique=true, IsForeignKey=false)]
		public tb_Chave tb_Chave
		{
			get
			{
				return this._tb_Chave.Entity;
			}
			set
			{
				tb_Chave previousValue = this._tb_Chave.Entity;
				if (((previousValue != value) 
							|| (this._tb_Chave.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Chave.Entity = null;
						previousValue.tb_Usuario = null;
					}
					this._tb_Chave.Entity = value;
					if ((value != null))
					{
						value.tb_Usuario = this;
					}
					this.SendPropertyChanged("tb_Chave");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_Lista", Storage="_tb_Listas", ThisKey="id", OtherKey="idUsuario")]
		public EntitySet<tb_Lista> tb_Listas
		{
			get
			{
				return this._tb_Listas;
			}
			set
			{
				this._tb_Listas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Usuario_tb_SenhaAlternativa", Storage="_tb_SenhaAlternativa", ThisKey="id", OtherKey="idUsuario", IsUnique=true, IsForeignKey=false)]
		public tb_SenhaAlternativa tb_SenhaAlternativa
		{
			get
			{
				return this._tb_SenhaAlternativa.Entity;
			}
			set
			{
				tb_SenhaAlternativa previousValue = this._tb_SenhaAlternativa.Entity;
				if (((previousValue != value) 
							|| (this._tb_SenhaAlternativa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_SenhaAlternativa.Entity = null;
						previousValue.tb_Usuario = null;
					}
					this._tb_SenhaAlternativa.Entity = value;
					if ((value != null))
					{
						value.tb_Usuario = this;
					}
					this.SendPropertyChanged("tb_SenhaAlternativa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Listas(tb_Lista entity)
		{
			this.SendPropertyChanging();
			entity.tb_Usuario = this;
		}
		
		private void detach_tb_Listas(tb_Lista entity)
		{
			this.SendPropertyChanging();
			entity.tb_Usuario = null;
		}
	}
}
#pragma warning restore 1591
